services:
  - type: web
    name: realestate-proxy
    env: docker
    dockerContext: ./realestate-proxy
    dockerfilePath: ./realestate-proxy/Dockerfile
    envVars:
      - key: PORT
        value: 3001
    autoDeploy: false
