-- Phase 18: Title Company Portal Schema
-- 1. Create title_companies table
CREATE TABLE IF NOT EXISTS public.title_companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    contact_email TEXT,
    contact_phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- 2. Create closing_codes table
CREATE TABLE IF NOT EXISTS public.closing_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    deal_id UUID REFERENCES public.deals(id) ON DELETE CASCADE,
    code TEXT NOT NULL UNIQUE,
    status TEXT CHECK (status IN ('ACTIVE', 'USED', 'EXPIRED')) DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- 3. Add title tracking columns to deals
ALTER TABLE public.deals
ADD COLUMN IF NOT EXISTS escrow_status TEXT CHECK (
        escrow_status IN ('PENDING', 'CONFIRMED', 'FAILED')
    ) DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS title_status TEXT CHECK (
        title_status IN ('PENDING', 'CLEAR', 'ISSUES_FOUND')
    ) DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS title_company_id UUID REFERENCES public.title_companies(id),
    ADD COLUMN IF NOT EXISTS closing_code TEXT;
-- RLS Enforcement
ALTER TABLE public.title_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.closing_codes ENABLE ROW LEVEL SECURITY;
-- Policies
CREATE POLICY "Allow authenticated read access to title companies" ON public.title_companies FOR
SELECT TO authenticated USING (true);
-- Closing codes can be generated by system and read by specific roles, but for the MVP we will keep it simple.
CREATE POLICY "Allow authenticated read to closing codes" ON public.closing_codes FOR
SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert to closing codes" ON public.closing_codes FOR
INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update to closing codes" ON public.closing_codes FOR
UPDATE TO authenticated USING (true) WITH CHECK (true);